const fs=require('fs'),path=require('path');const {chromium,firefox,webkit}=require('playwright');const {default:AxeBuilder}=require('@axe-core/playwright');const root=path.resolve(__dirname,'..');const base=process.env.AUDIT_URL||'http://127.0.0.1:4330/hornigold-preview';const langs=['pl','en','de','zh-hans','uk','es','it'];const routes=JSON.parse(fs.readFileSync(root+'/routes.json'));const routeFor=(lang,key)=>routes.find(r=>r.startsWith('/'+lang+'/')&&fs.readFileSync(root+'/site'+decodeURI(r)+'index.html','utf8').includes('data-page-key="'+key+'"'));
const results=[];const requireTrue=(test,msg)=>{if(!test)throw Error(msg)};
(async()=>{for(const [engine,type] of Object.entries({chromium,firefox,webkit})){const b=await type.launch();for(const width of [375,1366])for(const lang of langs){const c=await b.newContext({viewport:{width,height:900}});const p=await c.newPage();p.setDefaultTimeout(10000);let external=[];let js=[];p.on('pageerror',e=>js.push(e.message));await c.route('https://www.google.com/**',r=>{external.push(r.request().url());return r.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html lang="en"><title>Test map fixture</title><body>Test</body></html>'})});try{
await p.goto(base+routeFor(lang,'lokalizacja'));requireTrue(external.length===0,'Google before consent');requireTrue(await p.locator('[data-walk-viewer] iframe').count()===0,'frame before consent');
await p.locator('.legal-footer [data-privacy-open]').click();requireTrue(await p.locator('#privacy-dialog').evaluate(d=>d.open),'dialog not open');requireTrue(!await p.locator('#privacy-dialog [name=maps]').isChecked(),'prechecked consent');
if(engine==='chromium'){const axe=await new AxeBuilder({page:p}).include('#privacy-dialog').withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();requireTrue(!axe.violations.length,'dialog axe '+axe.violations.map(x=>x.id));}
for(let i=0;i<12;i++){await p.keyboard.press('Tab');requireTrue(await p.evaluate(()=>document.querySelector('#privacy-dialog').contains(document.activeElement)),'focus escapes modal');}
await p.keyboard.press('Escape');requireTrue(!await p.locator('#privacy-dialog').evaluate(d=>d.open),'Escape');requireTrue(external.length===0,'Escape granted');
await p.locator('.legal-footer [data-privacy-open]').click();await p.locator('#privacy-dialog [data-privacy-necessary]').click();await p.reload();requireTrue(await p.locator('#privacy-notice').isHidden(),'refusal not saved');requireTrue(!external.length,'request after refusal');
await p.locator('[data-walk-load]').click();await p.locator('#privacy-dialog [name=maps]').check();await p.locator('#privacy-dialog [data-privacy-save]').click();await p.waitForSelector('[data-walk-viewer] iframe');requireTrue(external.length>0,'maps not loaded after consent');
await p.locator('.legal-footer [data-privacy-open]').click();await p.locator('#privacy-dialog [data-privacy-necessary]').click();requireTrue(await p.locator('[data-walk-viewer] iframe').count()===0,'withdrawal did not remove iframe');
const n=external.length;await p.reload();requireTrue(external.length===n,'withdrawal not persisted');
await p.evaluate(()=>localStorage.setItem('hornigold-privacy',JSON.stringify({version:'2026-10-06.1',maps:true,time:Date.now()-181*86400000})));await p.reload();requireTrue(await p.locator('[data-walk-viewer] iframe').count()===0,'expired consent loaded maps');
await p.locator('.legal-footer [data-privacy-open]').click();await p.locator('[data-privacy-clear]').click();requireTrue(await p.evaluate(()=>localStorage.getItem('hornigold-privacy')===null&&localStorage.getItem('hornigold-language')===null),'clear failed');await p.keyboard.press('Escape');
await p.goto(base+routeFor(lang,'dokumenty'));requireTrue(await p.locator('.legal-content section').count()===6,'missing policies');const link=p.locator('.legal-content a[download]');const pdf=await c.request.get(new URL(await link.getAttribute('href'),base).href);requireTrue(pdf.status()===200&&(await pdf.body()).subarray(0,4).toString()==='%PDF','PDF inaccessible');requireTrue(!js.length,'JS '+js.join(','));
if(engine==='chromium'&&width===375&&['pl','zh-hans'].includes(lang)){await p.locator('.legal-footer [data-privacy-open]').click();await p.screenshot({path:'/tmp/privacy-'+lang+'.png'});}
results.push({engine,width,lang,pass:true,googleRequestsWereIntercepted:true});
}catch(e){results.push({engine,width,lang,error:e.message})}await c.close();}await b.close();console.log(engine+' complete');}fs.writeFileSync('/tmp/hornigold-privacy-v23.json',JSON.stringify({date:new Date().toISOString(),cases:results.length,results,failures:results.filter(x=>!x.pass)},null,2));console.log(JSON.stringify(results.filter(x=>!x.pass)));})();
