// Local cold-context lab measurements; not Lighthouse or field Core Web Vitals.
const fs=require('node:fs'),path=require('node:path');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),base=process.env.AUDIT_URL||'http://127.0.0.1:4342';
if(!['127.0.0.1','localhost'].includes(new URL(base).hostname))throw Error('Only loopback QA is permitted');
const all=JSON.parse(fs.readFileSync(root+'/routes.json'));const routes=all.filter(r=>r.split('/').length===3||r.includes('/club-hornigold/'));routes.push('/pl/pokoje/classic/','/pl/miasto-i-okolice/','/pl/miasto-i-okolice/gastronomia/','/pl/lokalizacja/','/pl/dokumenty/');
let browser;
(async()=>{browser=await chromium.launch({headless:true});const results=[];
for(const route of routes)for(const width of [375,1366]){const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'});const blocked=[];await context.route('**/*',r=>{if(new URL(r.request().url()).origin===new URL(base).origin)return r.continue();blocked.push(r.request().url());return r.abort()});const page=await context.newPage();
await page.addInitScript(()=>{window.__lab={lcp:0,cls:0};new PerformanceObserver(list=>{for(const x of list.getEntries())window.__lab.lcp=x.startTime}).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(list=>{for(const x of list.getEntries())if(!x.hadRecentInput)window.__lab.cls+=x.value}).observe({type:'layout-shift',buffered:true});});
const failed=[];page.on('pageerror',e=>failed.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push('HTTP '+r.status())});
await page.goto(base+route,{waitUntil:'load'});await page.waitForTimeout(1000);
const value=await page.evaluate(()=>{const nav=performance.getEntriesByType('navigation')[0];const resources=performance.getEntriesByType('resource');return {ttfbMs:nav.responseStart-nav.requestStart,domContentLoadedMs:nav.domContentLoadedEventEnd,loadMs:nav.loadEventEnd,lcpMs:window.__lab.lcp,cls:window.__lab.cls,transferBytes:nav.transferSize+resources.reduce((n,x)=>n+x.transferSize,0),resourceCount:resources.length,overflow:document.documentElement.scrollWidth>innerWidth+1,missingImages:[...document.images].filter(x=>x.loading!=='lazy'&&(!x.complete||x.naturalWidth===0)).map(x=>x.getAttribute('src'))}});
results.push({route,width,...value,blockedExternal:blocked,errors:failed});if(route==='/pl/')await page.screenshot({path:root+'/docs/seo/home-'+width+'.png',fullPage:false});await context.close();}
await browser.close();const sorted=results.map(x=>x.lcpMs).sort((a,b)=>a-b);const report={date:new Date().toISOString(),base,cases:results.length,summary:{medianLcpMs:sorted[Math.floor(sorted.length/2)],maxLcpMs:Math.max(...sorted),maxCls:Math.max(...results.map(x=>x.cls)),maxTransferBytes:Math.max(...results.map(x=>x.transferBytes))},failures:results.filter(x=>x.errors.length||x.blockedExternal.length||x.overflow||x.missingImages.length),results,limits:['Loopback HTTP on Mac mini, headless Chromium, no CPU or network throttling, cold browser context per page','LCP and CLS observed for 1 second after load only; no interaction/INP measurement','These are lab observations, not field CWV or guaranteed production performance']};fs.writeFileSync(root+'/docs/seo/performance-local.json',JSON.stringify(report,null,2));console.log(JSON.stringify({cases:report.cases,...report.summary,failures:report.failures.length}));process.exitCode=report.failures.length?1:0;
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1});
