// Isolated local browser fixtures; all requests intercepted, no Meta event is transmitted.
const fs=require('fs'),path=require('path');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),copy=JSON.parse(fs.readFileSync(root+'/integrations/meta/consent-copy.json'));
const privacy=fs.readFileSync(root+'/integrations/meta/privacy-marketing.js','utf8'),pixel=fs.readFileSync(root+'/integrations/meta/pixel.js','utf8');
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
(async()=>{const b=await chromium.launch();const results=[];for(const [lang,t] of Object.entries(copy))for(const width of [375,1366]){
 const c=await b.newContext({viewport:{width,height:900}});let meta=0;
 const html=`<!doctype html><html lang="${lang}"><head><meta name="hornigold-meta-pixel" content="2174344740165965"></head><body data-page-key="pokoje"><a href="tel:+48608662707">Contact</a><a data-privacy-open href="#privacy">Privacy</a><section id="privacy-notice"><button data-privacy-necessary>Only necessary</button></section><dialog id="privacy-dialog" data-cleared="Cleared"><button data-privacy-close>Close</button><h2>${esc(t.notice)}</h2><label><input name="maps" type="checkbox">Maps</label><label><input name="marketing" type="checkbox" aria-describedby="marketing-detail">${esc(t.marketing)}</label><p id="marketing-detail">${esc(t.marketingDetail)}</p><button data-privacy-necessary>Only necessary</button><button data-privacy-save>Save</button><button data-privacy-clear>Clear</button><p role="status"></p></dialog><script>${privacy}</script><script>${pixel}</script></body></html>`;
 await c.route('**/*',r=>{const u=r.request().url();if(u.startsWith('https://connect.facebook.net/')){meta++;return r.fulfill({contentType:'text/javascript',body:'/* Intercepted SDK; no data sent */'})}return r.fulfill({contentType:'text/html',body:html})});
 const p=await c.newPage();await p.goto('https://hornigold.pl/pl/');if(meta)throw Error('request before consent');
 await p.locator('[data-privacy-open]').click();if(await p.locator('[name=marketing]').isChecked())throw Error('prechecked');await p.locator('[name=maps]').check();await p.locator('[data-privacy-save]').click();if(meta)throw Error('map permission granted ads');
 await p.locator('[data-privacy-open]').click();await p.locator('[name=marketing]').check();await p.locator('[data-privacy-save]').click();await p.waitForFunction(()=>document.querySelector('[data-hornigold-meta]'));
 await p.locator('a[href^="tel:"]').click();const events=await p.evaluate(()=>Array.from(window.fbq.queue).filter(x=>x[0]==='track').map(x=>({name:x[1],id:x[3].eventID})));if(events.map(x=>x.name).join(',')!=='PageView,ViewContent,Contact'||new Set(events.map(x=>x.id)).size!==3)throw Error('duplicate/missing event');
 await p.locator('[data-privacy-open]').click();await p.locator('#privacy-dialog [data-privacy-necessary]').click();await p.waitForLoadState();if(await p.evaluate(()=>window.HornigoldPrivacy.allowsMarketing()))throw Error('withdrawal failed');const n=meta;await p.reload();if(meta!==n)throw Error('request after withdrawal');
 await p.evaluate(()=>localStorage.setItem('hornigold-privacy',JSON.stringify({version:'2026-10-06.1',maps:true,time:Date.now()})));await p.reload();if(await p.evaluate(()=>window.HornigoldPrivacy.allowsMarketing()))throw Error('legacy consent accepted');if(meta!==n)throw Error('legacy granted ads');
 results.push({lang,width,pass:true,networkIntercepted:true});await c.close();
}await b.close();const report={date:'2026-10-09',cases:results.length,results,metaEventsDelivered:false,limitations:['Isolated fixtures, not production or Meta Test Events; SDK intercepted.','Account-specific privacy HTML/PDF and production consent/CSP activation remain blocked.']};fs.writeFileSync(root+'/docs/seo/meta-staged-browser-2026-10-09.json',JSON.stringify(report,null,2));console.log(JSON.stringify({cases:results.length,errors:0,deliveredToMeta:false}));})().catch(e=>{console.error(e);process.exit(1)});
